### ISSUE TITLE
Want to help. Need documentation

### ISSUE THREAD

**Issue by AurelienFT** [kebasyaty/mango-orm#2]
Hello,

I'm currently looking for an ORM based on mongodb in RUST. I wanted to do it myself but I find out your repository and I think it will be better if I contribute than doing mine on my side.

But I don't find any documentations or anything to start help. Can we create a discussion on a instant message system, I can help you make the documentations and I have some knowledge on proc macros

**Comment by kebasyaty** [comment]
Hello,

Thank you for message.
My English is bad. I actively use the Google translator and if this is not a problem, it will be interesting to develop and support this project together.

It's good that you have experience with macros (I recently started to master them), your experience will be valuable.

Help with documentation is also needed.

My contacts:
viber: +380964488677
telegram: @kebasyaty

**Comment by AurelienFT** [comment]
Ok no problem. I added you but I can't send you messages. Can you add me too ? @AurelienFT
