### ISSUE TITLE
Separate ORM from Form dependencies

### ISSUE THREAD

**Issue by slyons** [kebasyaty/mango-orm#7]
This crate might be better served if the Form/Admin panel functionality was separated from the ORM itself. That would reduce the crate complexity and simplify testing. The widgets/form pieces could be wrappers coming from a separate Wrapper type.

I'd be willing to put together a PR that demonstrates my point if that would help.

**Comment by kebasyaty** [comment]
Hi!
I have very bad English, I crawl
google translator, I hope we understand each other.
Ваше видение проекта мне представляется интересным.
I would be glad if you contribute to the development of the project.

**Comment by kebasyaty** [comment]
1.
<<This crate might be better served if the Form/Admin panel functionality was separated from the ORM itself.>>
Forms are not used for the admin pane.
Forms are used for web development.
2.
<<The widgets/form pieces could be wrappers coming from a separate Wrapper type.>>
2.1.For such a solution, you need to take into account that it is convenient to create a map of widgets.
2.2.Widgets are used for both Forms and Models.

Telegram: @kebasyaty

P.S.
1.Dynamic widgets are useless without an admin panel.
2.I have a vision problem, when the situation improves, i have an idea to add two more types of widget.
